// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {youtube} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SearchYoutube(arg1:string):Promise<youtube.Playlist>;
